Vladimir feature
Vladimir-Zimin226/animal-shelter pull request #37
Opened 2024-06-18 15:03 UTC by Vladimir-Zimin226

2024-06-19 09:41 UTC, OlgaLugacheva commented on src/main/java/pro/sky/animal_shelter/service/implementations/PhotoOfPetService.java
> +            Report report = reportService.findReportByUserId(Long.valueOf(userId));
как такое возможно, если в метод должен передаваться Users

2024-06-19 18:09 UTC, OlgaLugacheva requested changes

2024-06-19 18:09 UTC, OlgaLugacheva commented on src/main/java/pro/sky/animal_shelter/entity/PhotoOfPet.java
> +    @OneToOne(mappedBy = "photoOfPet")
mappedBy тут не нужен, у вас же нет ссылки в Report 
или нужно поправить тогда вот это поле но уже в Report 
    @Column(name = "photo")
    private String photoOfPet; 

на тип сущности, иначе свалиться с ошибкой. Смотря, что вы тут хотели сделать

2024-06-19 18:09 UTC, OlgaLugacheva commented on src/main/java/pro/sky/animal_shelter/listener/TelegramBotUpdatesListener.java
> +        message.replyMarkup(createBackKeyboard());
вот эта строка явно должна быть до команды execute

2024-06-19 18:09 UTC, OlgaLugacheva commented on src/main/java/pro/sky/animal_shelter/listener/TelegramBotUpdatesListener.java
> +        message.replyMarkup(createBackKeyboard());
возможно, что  должен либо после этого метода либо в нем вызываться 
handleContactInfoProcess но уже с поступившим ответом на вышеобозначенный вопрос. 
Т.е. фактически сейчас вы не обрабатываете ответ пользователя, а игнорируете. 
Либо эта обработка должна быть в главном методе process. Возникнет вопрос, если такой еще не возникал, как сообщения пользователя для ветки   handleContactInfo отличить от любого другого. Для этого можно заводить флаг - что -то у вас подобное есть, и сбрасывать его после завершения обработки данных.

2024-06-19 18:09 UTC, OlgaLugacheva commented on src/main/java/pro/sky/animal_shelter/listener/TelegramBotUpdatesListener.java
> +
после того, как пользователь жмет на "кнопку начать процесс" нужно ему дать отправить второй апдейт уже с фото и описанием,и обрабатывать в отдельном методе этот новый апдейт, т.е. я бы ожидала, что в ответ на нажатие этой кнопки получу сообщение вида "Отправь фото с описанием" и следующим шагом мой ответ бы обрабатывался

2024-06-19 18:09 UTC, OlgaLugacheva commented on src/main/java/pro/sky/animal_shelter/listener/TelegramBotUpdatesListener.java
> +                .orElseThrow(() -> new RuntimeException("User not found"));
если пользователь не имеет прав отправлять отчет (т.е. вы его не нашли в базе),
то ему нужно об это сообщить, а не просто бросить исключение в коде

2024-06-20 07:48 UTC, Vladimir-Zimin226 commented on src/main/java/pro/sky/animal_shelter/service/implementations/PhotoOfPetService.java
> +            Report report = reportService.findReportByUserId(Long.valueOf(userId));
Этого метода нет, артефакт, уже удален из пулл-реквеста

2024-06-20 07:49 UTC, Vladimir-Zimin226 commented on src/main/java/pro/sky/animal_shelter/entity/PhotoOfPet.java
> +    @OneToOne(mappedBy = "photoOfPet")
Это тоже от старого кода, photoOfPet сейчас должно записаться в таблицу report_table в виде String

2024-06-20 07:50 UTC, Vladimir-Zimin226 commented on src/main/java/pro/sky/animal_shelter/listener/TelegramBotUpdatesListener.java
> +        message.replyMarkup(createBackKeyboard());
Пофиксил)

2024-06-20 07:50 UTC, Vladimir-Zimin226 commented on src/main/java/pro/sky/animal_shelter/listener/TelegramBotUpdatesListener.java
> +
Я это реализовал, но все равно работает некорректно, изменения в последнем коммите

2024-06-20 07:51 UTC, Vladimir-Zimin226 commented on src/main/java/pro/sky/animal_shelter/listener/TelegramBotUpdatesListener.java
> +                .orElseThrow(() -> new RuntimeException("User not found"));
Это исправил, добавил отправку сообщения

2024-06-21 12:01 UTC, OlgaLugacheva requested changes

2024-06-21 12:01 UTC, OlgaLugacheva commented on src/main/java/pro/sky/animal_shelter/listener/TelegramBotUpdatesListener.java
> +            case "Начать процесс":
так работать не будет, так как мы тут должны процессит новый update а в этом случае будет процесситься старый - коллбэк "Начать процесс". Я не просто так в примере вынесла его наверх перед свичем

2024-06-21 12:03 UTC, OlgaLugacheva requested changes

2024-06-21 12:03 UTC, OlgaLugacheva commented on src/main/java/pro/sky/animal_shelter/listener/TelegramBotUpdatesListener.java
> +        switch (text) {
вот тут мето проверке а не включен ли специальный режим 

```
private void handleUpdate(String chatId, String text, String telegramId, Update update) throws IOException {
    if (isPhotoProcessing) {
        uploadPhoto(chatId, update);
    }

```

2024-06-24 04:32 UTC, merged