Dev
Vladimir-Zimin226/animal-shelter pull request #52
Opened 2024-06-27 08:52 UTC by Vladimir-Zimin226

2024-06-27 18:30 UTC, OlgaLugacheva requested changes

2024-06-27 18:30 UTC, OlgaLugacheva commented on src/main/java/pro/sky/animal_shelter/repository/CatsRepository.java
> +    Cats findCatsById(long id);
Optional

2024-06-27 18:30 UTC, OlgaLugacheva commented on src/main/java/pro/sky/animal_shelter/service/implementations/CatServiceImpl.java
> +    public Cats createCat(Cats cat) {
метод используется только в тестах, он точно нужен?

2024-06-30 03:15 UTC, Vladimir-Zimin226 commented on src/main/java/pro/sky/animal_shelter/repository/CatsRepository.java
> +    Cats findCatsById(long id);
Это поправил)

2024-06-30 03:16 UTC, Vladimir-Zimin226 commented on src/main/java/pro/sky/animal_shelter/service/implementations/CatServiceImpl.java
> +    public Cats createCat(Cats cat) {
Решили что не будем удалять, пусть остается)

2024-06-30 03:16 UTC, merged